ALPHA BETA
   0 1 2 3 4 5 6 7 8 9
  +---------------------+
0 |X 0 0 2 X 0 X 0 0 0|
1 |X 0 0 X X 0 0 X 0 0|
2 |1 0 0 0 0 0 0 X 0 0|
3 |0 0 X X 0 0 0 0 X 0|
4 |0 0 0 X X 0 0 0 0 0|
5 |2 X X 0 0 1 0 0 0 0|
6 |0 X 0 0 0 0 0 0 0 1|
7 |X 0 0 0 X 2 X 0 X 0|
8 |0 0 0 0 1 0 0 0 0 0|
9 |0 0 0 0 0 X 0 0 0 2|
  +---------------------+
DEPTH: 1
Tiefe 1 - New best move for player 1: ((2, 0), (1, 1), (0, 1)) mit eval 32.89145833333333 und max eval -inf
Tiefe 1 - New best move for player 1: ((2, 0), (1, 1), (0, 2)) mit eval 34.183125000000004 und max eval 32.89145833333333
Tiefe 1 - New best move for player 1: ((2, 0), (1, 1), (1, 2)) mit eval 37.16645833333333 und max eval 34.183125000000004
Tiefe 1 - New best move for player 1: ((2, 0), (2, 1), (1, 1)) mit eval 38.04114583333333 und max eval 37.16645833333333
Tiefe 1 - New best move for player 1: ((2, 0), (2, 1), (0, 1)) mit eval 40.3328125 und max eval 38.04114583333333
Tiefe 1 - New best move for player 1: ((2, 0), (2, 1), (1, 2)) mit eval 42.23447916666667 und max eval 40.3328125
Max Eval 42.23447916666667 | Alpha 42.23447916666667 | beta inf | depth 1
Max Eval 42.23447916666667 | EVAL 42.674375 | Alpha 42.23447916666667 | beta inf | depth 1
Tiefe 1 - New best move for player 1: ((8, 4), (8, 2), (6, 0)) mit eval 42.674375 und max eval 42.23447916666667
best_move: ((8, 4), (8, 2), (6, 0))




DEPTH: 2
Found hash
stored depth 1 vs 2 42.674375 ((8, 4), (8, 2), (6, 0))
Tiefe 2 - New best move for player 1: ((2, 0), (1, 1), (0, 1)) mit eval 14.975375000000003 und max eval -inf
Tiefe 2 - New best move for player 1: ((2, 0), (1, 1), (0, 2)) mit eval 15.6702578125 und max eval 14.975375000000003
Tiefe 2 - New best move for player 1: ((2, 0), (1, 1), (1, 2)) mit eval 17.791875 und max eval 15.6702578125
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Tiefe 2 - New best move for player 1: ((2, 0), (2, 1), (1, 1)) mit eval 20.141718750000003 und max eval 17.791875
Tiefe 2 - New best move for player 1: ((2, 0), (2, 1), (0, 1)) mit eval 22.42921875 und max eval 20.141718750000003
Tiefe 2 - New best move for player 1: ((2, 0), (2, 1), (1, 2)) mit eval 22.87771875 und max eval 22.42921875
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Tiefe 2 - New best move for player 1: ((2, 0), (2, 1), (3, 0)) mit eval 23.0881015625 und max eval 22.87771875
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Tiefe 2 - New best move for player 1: ((2, 0), (3, 1), (4, 0)) mit eval 23.307624999999998 und max eval 23.0881015625
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Tiefe 2 - New best move for player 1: ((8, 4), (8, 3), (8, 8)) mit eval 24.934687500000003 und max eval 23.307624999999998
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Max Eval 24.934687500000003 | Alpha 24.934687500000003 | beta inf | depth 2
Cut off - Beta
Max Eval 24.934687500000003 | EVAL 24.726375000000004 | Alpha 24.934687500000003 | beta inf | depth 2
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Tiefe 2 - New best move for player 1: ((8, 4), (8, 2), (8, 8)) mit eval 25.188882812500005 und max eval 24.934687500000003
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Tiefe 2 - New best move for player 1: ((8, 4), (8, 1), (8, 8)) mit eval 25.593257812500006 und max eval 25.188882812500005
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
Cut off - Beta
best_move: ((8, 4), (8, 1), (8, 8))
Move Spieler 1 (Alpha Beta):  ((8, 4), (8, 1), (8, 8))
EVAL SPIELER 1:  42.50479166666666